name: notebooks
channels:
  - conda-forge
  - conda
  - pytorch
  - pypi
dependencies:
  - r-base=4
  - r-tidyverse
  - python                          
  - pip
  - pandas-profiling
  - rpy2                          
  - rsa                           
  - scikit-image                  
  - scikit-learn 
  - sklearn-pandas        
  - dask
  - pandas-datareader             
  - pandas-gbq                    
  - pandocfilters 
  - tensorboard                   
  - tensorboard-plugin-wit        
  - tensorflow                    
  - tensorflow-datasets           
  - tensorflow-estimator          
  - tensorflow-hub                
  - tensorflow-metadata           
  - tensorflow-probability        
  - torchtext                     
  - torchvision                   
  - tornado   
  - Keras                         
  - Keras-Preprocessing           
  - matplotlib                    
  - matplotlib-venn           
  - scipy                         
  - scs                           
  - seaborn       
  - nbconvert                     
  - nbformat                      
  - nest-asyncio                  
  - networkx                      
  - nibabel                       
  - nltk                          
  - notebook                      
  - numba                         
  - numexpr                       
  - numpy                         
  - oauth2client                  
  - oauthlib      
  - pytorch
  - pytorch-modules