name: notebooks
channels:
  - conda-forge
  - pytorch
  - pypi
dependencies:
  - r-base=4
  - r-essentials
  - r-tensorflow
  - r-keras
  - r-xgboost
  - r-mboost
  - r-ahaz
  - r-arules
  - r-BART
  - r-BayesTree
  - r-BDgraph
  - r-biglasso
  - r-Boruta
  - r-C50
  - r-caret
  - r-CORElearn
  - r-Cubist
  - r-deepnet
  - r-e1071 
  - r-earth
  - r-effects
  - r-elasticnet
  - r-evclass
  - r-frbs
  - r-gamboostLSS
  - r-gbm 
  - r-glmnet
  - r-glmpath
  - r-GMMBoost
  - r-gradDescent
  - r-grf
  - r-grplasso
  - r-grpreg
  - r-h2o
  - r-hda
  - r-hdm
  - r-ICEbox
  - r-ipred
  - r-kernlab (core)
  - r-klaR
  - r-lars
  - r-lasso2
  - r-LiblineaR
  - r-maptree
  - r-mboost
  - r-naivebayes
  - r-ncvreg
  - r-nnet
  - r-OneR
  - r-opusminer
  - r-pamr
  - r-party
  - r-partykit
  - r-pdp
  - r-penalized
  - r-picasso
  - r-plotmo
  - r-randomForest
  - r-randomForestSRC
  - r-ranger
  - r-rattle
  - r-Rborist
  - r-rdetools
  - r-relaxo
  - r-rgenoud
  - r-RGF
  - r-RLT
  - r-Rmalschains
  - r-ROCR
  - r-RoughSets
  - r-rpart
  - r-RPMM
  - r-RSNNS
  - r-RWeka
  - r-RXshrink
  - r-sda
  - r-stabs
  - r-SuperLearner
  - r-tensorflow
  - r-tree
  - r-varSelRF
  - r-xgboost
  - r-mlr
  - r-tidyverse
  - r-boot
  - r-caret
  - python                          
  - pip
  - pandas-profiling
  - rpy2                          
  - rsa                           
  - scikit-image                  
  - scikit-learn 
  - sklearn-pandas        
  - dask
  - pandas-datareader             
  - pandas-gbq                    
  - pandocfilters 
  - tensorboard                   
  - tensorboard-plugin-wit        
  - tensorflow                    
  - tensorflow-datasets           
  - tensorflow-estimator          
  - tensorflow-hub                
  - tensorflow-metadata           
  - tensorflow-probability        
  - torchtext                     
  - torchvision                   
  - tornado   
  - Keras                         
  - Keras-Preprocessing           
  - matplotlib                    
  - matplotlib-venn           
  - scipy                         
  - scs                           
  - seaborn       
  - nbconvert                     
  - nbformat                      
  - nest-asyncio                  
  - networkx                      
  - nibabel                       
  - nltk                          
  - notebook                      
  - numba                         
  - numexpr                       
  - numpy                         
  - oauth2client                  
  - oauthlib      
  - pytorch