name: example-environment
channels:
  - conda-forge
dependencies:
  - r-base=4
  - r-tidyverse
  - python                          3.8.0
  - pip
  - pandas-profiling
  - rpy2                          
  - rsa                           
  - scikit-image                  
  - scikit-learn 
  - sklearn                       
  - sklearn-pandas        
  - dask
  - pandas-datareader             
  - pandas-gbq                    
  - pandocfilters 
  - tensorboard                   
  - tensorboard-plugin-wit        
  - tensorboardcolab              
  - tensorflow                    
  - tensorflow-addons             
  - tensorflow-datasets           
  - tensorflow-estimator          
  - tensorflow-gcs-config         
  - tensorflow-hub                
  - tensorflow-metadata           
  - tensorflow-privacy            
  - tensorflow-probability        
  - torch                         
  - torchsummary                  
  - torchtext                     
  - torchvision                   
  - tornado   
  - Keras                         
  - Keras-Preprocessing           
  - keras-vis         
  - matplotlib                    
  - matplotlib-venn           
  - scipy                         
  - screen-resolution-extra       
  - scs                           
  - seaborn       
  - nbconvert                     
  - nbformat                      
  - nest-asyncio                  
  - networkx                      
  - nibabel                       
  - nltk                          
  - notebook                      
  - np-utils                      
  - numba                         
  - numexpr                       
  - numpy                         
  - nvidia-ml-py3                 
  - oauth2client                  
  - oauthlib      