install.packages("tidyverse", repos="https://cran.microsoft.com/snapshot/2020-10-10/")
install.packages("rmarkdown", repos="https://cran.microsoft.com/snapshot/2020-10-10/")
install.packages("httr", repos="https://cran.microsoft.com/snapshot/2020-10-10/")
install.packages("shinydashboard", repos="https://cran.microsoft.com/snapshot/2020-10-10/")
install.packages('leaflet', repos="https://cran.microsoft.com/snapshot/2020-10-10/")
install.packages('ggplot2', repos="https://cran.microsoft.com/snapshot/2020-10-10/")
install.packages("gridExtra", repos="https://cran.microsoft.com/snapshot/2020-10-10/")
install.packages("hexbin", repos="https://cran.microsoft.com/snapshot/2020-10-10/")
install.packages("lubridate", repos="https://cran.microsoft.com/snapshot/2020-10-10/")
install.packages("readr", repos="https://cran.microsoft.com/snapshot/2020-10-10/")
install.packages("dplyr", repos="https://cran.microsoft.com/snapshot/2020-10-10/")
install.packages("magrittr", repos="https://cran.microsoft.com/snapshot/2020-10-10/")
install.packages("tidyr", repos="https://cran.microsoft.com/snapshot/2020-10-10/")
install.packages("knitr", repos="https://cran.microsoft.com/snapshot/2020-10-10/")
install.packages("shiny", repos="https://cran.microsoft.com/snapshot/2020-10-10/")
install.packages("DT", repos="https://cran.microsoft.com/snapshot/2020-10-10/")
install.packages("caTools", repos="https://cran.microsoft.com/snapshot/2020-10-10/")
install.packages("bitops", repos="https://cran.microsoft.com/snapshot/2020-10-10/")
install.packages("rprojroot", repos="https://cran.microsoft.com/snapshot/2020-10-10/")
install.packages("np", repos="https://cran.microsoft.com/snapshot/2020-10-10/")
install.packages("boot", repos="https://cran.microsoft.com/snapshot/2020-10-10/")
install.packages("learnr", repos="https://cran.microsoft.com/snapshot/2020-10-10/")
install.packages("here", repos="https://cran.microsoft.com/snapshot/2020-10-10/")
install.packages("ctv", repos="https://cloud.r-project.org/")
ctv::install.views("MachineLearning")


