install.packages("tidyverse")
install.packages("rmarkdown")
install.packages("httr")
install.packages("shinydashboard")
install.packages('leaflet')
install.packages('ggplot2')
writeLines("R_LIBS_USER=/srv/rlibs", "~/.Renviron")
