options(repos=structure(c(CRAN="https://cran.cnr.berkeley.edu/")))
install.packages("tidyverse")
install.packages("rmarkdown")
install.packages("httr")
install.packages("shinydashboard")
install.packages('leaflet')
install.packages('ggplot2')
